### ISSUE TITLE
Example of using via in method provides

### ISSUE THREAD

**Issue by bearded** [benhoskings/babushka.me#11]
Hello Ben,

I think would be good to add note in examples about possibility to use `via` in method `provides` like this:

``` ruby
dep 'dhcp3-server.bin' do
  installs {
    via [:lucid, :precise], 'dhcp3-server'
  }

  provides {
    via :lucid,   'dhcpd3'
    via :precise, 'dhcpd'
  }
end
```

**Comment by benhoskings** [comment]
Came across this doing a bit of a cleanup - never did quite get to it I'm afraid!
